a = int(input("Pick a number: "))
b = int(input("Pick another number: "))
c = int(input("Pick a third number: "))

root1 = (-b + (b*b - 4*a*c)**0.5) / (2*a)
root2 = (-b - (b*b - 4*a*c)**0.5) / (2*a)
print()
print(root1)
print()
print(root2)